---
- name: Install Grafana
  hosts: all
  become: yes

  tasks:
    - name: Import Grafana GPG key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Update repositories cache and install Grafana
      ansible.builtin.apt:
        update_cache: yes
        name: grafana
        state: latest

    - name: Ensure Grafana is running and enabled on boot
      ansible.builtin.systemd:
        name: grafana-server
        enabled: yes
        state: started
